{
  ...
}:
{
  imports = [
    ./hyprland.nix
    ./persistence.nix
    ./zed
    ./firefox
    ./waybar/style_1.nix
    ./legacy/themes/blue-sky.nix
    ./ghostty
    ./legacy/fonts.nix
    ./legacy/background
    ./legacy/fastfetch.nix
    ./legacy/helper.nix
    ./nvim
  ];
}
